# Generated by Django 2.2.6 on 2019-11-23 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reprografica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('rating_medio', models.FloatField(default=0.0)),
                ('horario_abertura_semana_manha', models.FloatField()),
                ('horario_fecho_semana_manha', models.FloatField()),
                ('horario_abertura_semana_tarde', models.FloatField()),
                ('horario_fecho_semana_tarde', models.FloatField()),
                ('horario_abertura_fds_manha', models.FloatField()),
                ('horario_fecho_fds_manha', models.FloatField()),
                ('horario_abertura_fds_tarde', models.FloatField()),
                ('horario_fecho_fds_tarde', models.FloatField()),
                ('cartao_visita_preco', models.FloatField(default=-1.0)),
            ],
        ),
        migrations.CreateModel(
            name='A0',
            fields=[
                ('reprografia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.Reprografica')),
                ('cor_preco', models.FloatField(default=-1.0)),
                ('preto_branco_preco', models.FloatField(default=-1.0)),
                ('encadernacao', models.FloatField(default=-1.0)),
                ('digitalizacao', models.FloatField(default=-1.0)),
                ('plastificacao', models.FloatField(default=-1.0)),
            ],
        ),
        migrations.CreateModel(
            name='A1',
            fields=[
                ('reprografia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.Reprografica')),
                ('cor_preco', models.FloatField(default=-1.0)),
                ('preto_branco_preco', models.FloatField(default=-1.0)),
                ('encadernacao', models.FloatField(default=-1.0)),
                ('digitalizacao', models.FloatField(default=-1.0)),
                ('plastificacao', models.FloatField(default=-1.0)),
            ],
        ),
        migrations.CreateModel(
            name='A2',
            fields=[
                ('reprografia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.Reprografica')),
                ('cor_preco', models.FloatField(default=-1.0)),
                ('preto_branco_preco', models.FloatField(default=-1.0)),
                ('encadernacao', models.FloatField(default=-1.0)),
                ('digitalizacao', models.FloatField(default=-1.0)),
                ('plastificacao', models.FloatField(default=-1.0)),
            ],
        ),
        migrations.CreateModel(
            name='A3',
            fields=[
                ('reprografia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.Reprografica')),
                ('cor_preco', models.FloatField(default=-1.0)),
                ('preto_branco_preco', models.FloatField(default=-1.0)),
                ('encadernacao', models.FloatField(default=-1.0)),
                ('digitalizacao', models.FloatField(default=-1.0)),
                ('plastificacao', models.FloatField(default=-1.0)),
            ],
        ),
        migrations.CreateModel(
            name='A4',
            fields=[
                ('reprografia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.Reprografica')),
                ('cor_preco', models.FloatField(default=-1.0)),
                ('preto_branco_preco', models.FloatField(default=-1.0)),
                ('encadernacao', models.FloatField(default=-1.0)),
                ('digitalizacao', models.FloatField(default=-1.0)),
                ('plastificacao', models.FloatField(default=-1.0)),
            ],
        ),
        migrations.CreateModel(
            name='A5',
            fields=[
                ('reprografia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.Reprografica')),
                ('cor_preco', models.FloatField(default=-1.0)),
                ('preto_branco_preco', models.FloatField(default=-1.0)),
                ('encadernacao', models.FloatField(default=-1.0)),
                ('digitalizacao', models.FloatField(default=-1.0)),
                ('plastificacao', models.FloatField(default=-1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Tese',
            fields=[
                ('reprografia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.Reprografica')),
                ('preco', models.FloatField()),
            ],
        ),
    ]
