# Generated by Django 2.2.7 on 2019-12-26 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reprografia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('zona', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('webiste', models.CharField(default=-1, max_length=50)),
                ('contacto', models.IntegerField(default=-1, max_length=9)),
                ('email', models.CharField(default=-1, max_length=50)),
                ('rating_medio', models.FloatField(default=0.0)),
                ('horario_abertura_semana_manha', models.FloatField()),
                ('horario_fecho_semana_manha', models.FloatField()),
                ('horario_abertura_semana_tarde', models.FloatField()),
                ('horario_fecho_semana_tarde', models.FloatField()),
                ('horario_abertura_fds_manha', models.FloatField()),
                ('horario_fecho_fds_manha', models.FloatField()),
                ('horario_abertura_fds_tarde', models.FloatField()),
                ('horario_fecho_fds_tarde', models.FloatField()),
                ('cartao_visita_preco', models.FloatField(default=-1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Acinco',
            fields=[
                ('reprografia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.Reprografia')),
                ('frente_cor_preco', models.FloatField(default=-1.0)),
                ('frente_preto_branco_preco', models.FloatField(default=-1.0)),
                ('frente_verso_cor_preco', models.FloatField(default=-1.0)),
                ('frente_verso_preto_branco_preco', models.FloatField(default=-1.0)),
                ('encadernacao', models.FloatField(default=-1.0)),
                ('digitalizacao', models.FloatField(default=-1.0)),
                ('plastificacao', models.FloatField(default=-1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Adois',
            fields=[
                ('reprografia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.Reprografia')),
                ('frente_cor_preco', models.FloatField(default=-1.0)),
                ('frente_preto_branco_preco', models.FloatField(default=-1.0)),
                ('frente_verso_cor_preco', models.FloatField(default=-1.0)),
                ('frente_verso_preto_branco_preco', models.FloatField(default=-1.0)),
                ('encadernacao', models.FloatField(default=-1.0)),
                ('digitalizacao', models.FloatField(default=-1.0)),
                ('plastificacao', models.FloatField(default=-1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Aquatro',
            fields=[
                ('reprografia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.Reprografia')),
                ('frente_cor_preco', models.FloatField(default=-1.0)),
                ('frente_preto_branco_preco', models.FloatField(default=-1.0)),
                ('frente_verso_cor_preco', models.FloatField(default=-1.0)),
                ('frente_verso_preto_branco_preco', models.FloatField(default=-1.0)),
                ('encadernacao', models.FloatField(default=-1.0)),
                ('digitalizacao', models.FloatField(default=-1.0)),
                ('plastificacao', models.FloatField(default=-1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Atres',
            fields=[
                ('reprografia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.Reprografia')),
                ('frente_cor_preco', models.FloatField(default=-1.0)),
                ('frente_preto_branco_preco', models.FloatField(default=-1.0)),
                ('frente_verso_cor_preco', models.FloatField(default=-1.0)),
                ('frente_verso_preto_branco_preco', models.FloatField(default=-1.0)),
                ('encadernacao', models.FloatField(default=-1.0)),
                ('digitalizacao', models.FloatField(default=-1.0)),
                ('plastificacao', models.FloatField(default=-1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Aum',
            fields=[
                ('reprografia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.Reprografia')),
                ('frente_cor_preco', models.FloatField(default=-1.0)),
                ('frente_preto_branco_preco', models.FloatField(default=-1.0)),
                ('frente_verso_cor_preco', models.FloatField(default=-1.0)),
                ('frente_verso_preto_branco_preco', models.FloatField(default=-1.0)),
                ('encadernacao', models.FloatField(default=-1.0)),
                ('digitalizacao', models.FloatField(default=-1.0)),
                ('plastificacao', models.FloatField(default=-1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Azero',
            fields=[
                ('reprografia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.Reprografia')),
                ('frente_cor_preco', models.FloatField(default=-1.0)),
                ('frente_preto_branco_preco', models.FloatField(default=-1.0)),
                ('frente_verso_cor_preco', models.FloatField(default=-1.0)),
                ('frente_verso_preto_branco_preco', models.FloatField(default=-1.0)),
                ('encadernacao', models.FloatField(default=-1.0)),
                ('digitalizacao', models.FloatField(default=-1.0)),
                ('plastificacao', models.FloatField(default=-1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Tese',
            fields=[
                ('reprografia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.Reprografia')),
                ('preco', models.FloatField()),
            ],
        ),
    ]
