# Generated by Django 2.2.7 on 2019-12-09 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acinco',
            fields=[
                ('reprografia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.Reprografia')),
                ('frente_cor_preco', models.FloatField(default=-1.0)),
                ('frente_preto_branco_preco', models.FloatField(default=-1.0)),
                ('frente_verso_cor_preco', models.FloatField(default=-1.0)),
                ('frente_verso_preto_branco_preco', models.FloatField(default=-1.0)),
                ('encadernacao', models.FloatField(default=-1.0)),
                ('digitalizacao', models.FloatField(default=-1.0)),
                ('plastificacao', models.FloatField(default=-1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Adois',
            fields=[
                ('reprografia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.Reprografia')),
                ('frente_cor_preco', models.FloatField(default=-1.0)),
                ('frente_preto_branco_preco', models.FloatField(default=-1.0)),
                ('frente_verso_cor_preco', models.FloatField(default=-1.0)),
                ('frente_verso_preto_branco_preco', models.FloatField(default=-1.0)),
                ('encadernacao', models.FloatField(default=-1.0)),
                ('digitalizacao', models.FloatField(default=-1.0)),
                ('plastificacao', models.FloatField(default=-1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Aquatro',
            fields=[
                ('reprografia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.Reprografia')),
                ('frente_cor_preco', models.FloatField(default=-1.0)),
                ('frente_preto_branco_preco', models.FloatField(default=-1.0)),
                ('frente_verso_cor_preco', models.FloatField(default=-1.0)),
                ('frente_verso_preto_branco_preco', models.FloatField(default=-1.0)),
                ('encadernacao', models.FloatField(default=-1.0)),
                ('digitalizacao', models.FloatField(default=-1.0)),
                ('plastificacao', models.FloatField(default=-1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Atres',
            fields=[
                ('reprografia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.Reprografia')),
                ('frente_cor_preco', models.FloatField(default=-1.0)),
                ('frente_preto_branco_preco', models.FloatField(default=-1.0)),
                ('frente_verso_cor_preco', models.FloatField(default=-1.0)),
                ('frente_verso_preto_branco_preco', models.FloatField(default=-1.0)),
                ('encadernacao', models.FloatField(default=-1.0)),
                ('digitalizacao', models.FloatField(default=-1.0)),
                ('plastificacao', models.FloatField(default=-1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Aum',
            fields=[
                ('reprografia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.Reprografia')),
                ('frente_cor_preco', models.FloatField(default=-1.0)),
                ('frente_preto_branco_preco', models.FloatField(default=-1.0)),
                ('frente_verso_cor_preco', models.FloatField(default=-1.0)),
                ('frente_verso_preto_branco_preco', models.FloatField(default=-1.0)),
                ('encadernacao', models.FloatField(default=-1.0)),
                ('digitalizacao', models.FloatField(default=-1.0)),
                ('plastificacao', models.FloatField(default=-1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Azero',
            fields=[
                ('reprografia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.Reprografia')),
                ('frente_cor_preco', models.FloatField(default=-1.0)),
                ('frente_preto_branco_preco', models.FloatField(default=-1.0)),
                ('frente_verso_cor_preco', models.FloatField(default=-1.0)),
                ('frente_verso_preto_branco_preco', models.FloatField(default=-1.0)),
                ('encadernacao', models.FloatField(default=-1.0)),
                ('digitalizacao', models.FloatField(default=-1.0)),
                ('plastificacao', models.FloatField(default=-1.0)),
            ],
        ),
        migrations.RemoveField(
            model_name='a1',
            name='reprografia',
        ),
        migrations.RemoveField(
            model_name='a2',
            name='reprografia',
        ),
        migrations.RemoveField(
            model_name='a3',
            name='reprografia',
        ),
        migrations.RemoveField(
            model_name='a4',
            name='reprografia',
        ),
        migrations.RemoveField(
            model_name='a5',
            name='reprografia',
        ),
        migrations.DeleteModel(
            name='A0',
        ),
        migrations.DeleteModel(
            name='A1',
        ),
        migrations.DeleteModel(
            name='A2',
        ),
        migrations.DeleteModel(
            name='A3',
        ),
        migrations.DeleteModel(
            name='A4',
        ),
        migrations.DeleteModel(
            name='A5',
        ),
    ]
