# Generated by Django 2.2.6 on 2019-11-23 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reprografica',
            new_name='Reprografia',
        ),
    ]
