# Generated by Django 2.2.6 on 2019-12-23 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='A0',
            new_name='Acinco',
        ),
        migrations.RenameModel(
            old_name='A5',
            new_name='Adois',
        ),
        migrations.RenameModel(
            old_name='A1',
            new_name='Aquatro',
        ),
        migrations.RenameModel(
            old_name='A3',
            new_name='Atres',
        ),
        migrations.RenameModel(
            old_name='A4',
            new_name='Aum',
        ),
        migrations.RenameModel(
            old_name='A2',
            new_name='Azero',
        ),
    ]
