# Generated by Django 2.2.6 on 2019-11-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20191123_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reprografia',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
